name: Build and Deploy
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'

      - name: Replace GH_COMMIT_HASH 📝
        run: |
          sed -i "s/#{GH_COMMIT_HASH}#/${{ github.sha }}/g" src/components/footer/index.svelte

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
