name: Build and Deploy
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update npm 📦
        run: npm install -g npm@latest

      - name: Update node-gyp 🔨
        run: npm install -g node-gyp@latest

      - name: Install and Build 🔧
        run: |
          npm ci
          NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
